import { extractManagedBlock, readTextIfExists, mergeManagedBlock, resolveInside } from "./files.mjs";
import {
  adapterSkillMetadata,
  canonicalSkillMetadata,
  validateSkillDocument,
} from "./skill-documents.mjs";

const GENERATED_HEADER = "Generated by Gongxu from `.ai/blueprint.json`. Edit the blueprint and recompile instead of editing this file directly.";

function title(text) {
  return String(text)
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(" ");
}

function bullets(values, empty = "- None recorded.") {
  return values.length > 0 ? values.map((value) => `- ${value}`).join("\n") : empty;
}

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function addFile(files, path, content, ownership = "file", mode = 0o644) {
  files.set(path, { path, content: content.endsWith("\n") ? content : `${content}\n`, ownership, mode });
}

function addSkillFile(files, path, content) {
  const normalized = content.endsWith("\n") ? content : `${content}\n`;
  const validation = validateSkillDocument(path, normalized);
  if (validation.errors.length > 0) {
    throw new Error(`Generated Skill document is invalid: ${validation.errors.join(" ")}`);
  }
  addFile(files, path, normalized);
}

function renderProfile(blueprint) {
  const project = blueprint.project;
  return `# ${project.name}

> ${GENERATED_HEADER}

${project.summary}

## Classification

- Stage: ${project.stage}
- Kind: ${project.kind}

## Primary Users

${bullets(project.primaryUsers)}

## Domains

${bullets(project.domains)}

## Confirmed Constraints

${bullets(project.constraints)}

## Assumptions

${bullets(blueprint.evidence.assumptions)}

## Open Questions

${blueprint.evidence.unknowns.length > 0
    ? blueprint.evidence.unknowns.map((item) => `- **${item.id}:** ${item.question} Impact: ${item.impact}`).join("\n")
    : "- None blocking the current blueprint."}
`;
}

function renderModule(module) {
  return `### ${module.name} \`${module.id}\`

- State: ${module.planned ? "planned" : "present"}
- Paths: ${module.paths.map((path) => `\`${path}\``).join(", ") || "none"}
- Dependencies: ${module.dependencies.map((dependency) => `\`${dependency}\``).join(", ") || "none"}
- Responsibilities:
${module.responsibilities.length > 0 ? module.responsibilities.map((item) => `  - ${item}`).join("\n") : "  - None recorded."}
`;
}

function renderRepoMap(blueprint) {
  const current = blueprint.architecture.current;
  const target = blueprint.architecture.target;
  return `# Repository Map

> ${GENERATED_HEADER}

## Start Here

- Project profile: \`.ai/project/profile.md\`
- Evidence ledger: \`.ai/project/facts.json\`
- Architecture model: \`.ai/architecture/model.json\`
- Project rules: \`.ai/rules/\`
- Task skills: \`.ai/skills/\`
- Verification: \`.ai/verification/checks.json\`

## Current Architecture

${current.summary}

- Style: ${current.style}

${current.modules.length > 0 ? current.modules.map(renderModule).join("\n") : "No modules were confirmed from repository evidence."}

## Target Architecture

- Status: ${target.status}
- Style: ${target.style}

${target.summary}

${target.modules.length > 0 ? target.modules.map(renderModule).join("\n") : "No target modules were confirmed."}
`;
}

function renderCurrentArchitecture(blueprint) {
  const architecture = blueprint.architecture;
  return `# Architecture

> ${GENERATED_HEADER}

## Observed Current State

- Style: ${architecture.current.style}

${architecture.current.summary}

${architecture.current.modules.length > 0 ? architecture.current.modules.map(renderModule).join("\n") : "No current modules were confirmed."}

## Desired State

- Status: ${architecture.target.status}
- Style: ${architecture.target.style}

${architecture.target.summary}

${architecture.target.status === "proposed" ? "This target remains a proposal and must not be enforced as confirmed architecture." : "The target state is confirmed for this blueprint."}
`;
}

function renderBoundaries(blueprint) {
  return `# Architecture Boundaries

> ${GENERATED_HEADER}

${blueprint.architecture.boundaries.length > 0
    ? blueprint.architecture.boundaries.map((boundary) => `## ${title(boundary.id)}

- Policy: **${boundary.policy}**
- From: \`${boundary.from}\`
- To: \`${boundary.to}\`
- Rationale: ${boundary.rationale}
- Sources: ${boundary.sourceFactIds.map((id) => `\`${id}\``).join(", ")}
`).join("\n")
    : "No enforceable architecture boundaries were confirmed."}
`;
}

function renderRuleScope(scope, rules) {
  return `# ${title(scope)} Rules

> ${GENERATED_HEADER}

${rules.map((rule) => `## ${title(rule.id)}

- Severity: **${rule.severity}**
- Rule: ${rule.statement}
- Rationale: ${rule.rationale}
- Sources: ${rule.sourceFactIds.map((id) => `\`${id}\``).join(", ")}
${rule.checkId ? `- Check: \`${rule.checkId}\`` : ""}
${rule.approvalRequired ? "- Approval required: yes" : ""}
`).join("\n")}
`;
}

function renderCanonicalSkill(skill, checks) {
  const metadata = canonicalSkillMetadata(skill);
  const checkNames = skill.verificationCheckIds.map((id) => checks.get(id));
  return `---
name: ${metadata.name}
description: ${JSON.stringify(metadata.description)}
---

# ${skill.name}

## Context

Read these project sources before acting:

${skill.context.length > 0 ? skill.context.map((path) => `- \`${path}\``).join("\n") : "- `.ai/project/repo-map.md`"}

## Workflow

${skill.steps.map((step, index) => `${index + 1}. ${step}`).join("\n")}

## Verification

${checkNames.length > 0 ? checkNames.map((check) => `- Run \`${check.command}\` from \`${check.cwd || "."}\`.`).join("\n") : "- Follow `.ai/verification/checks.json` for checks relevant to the changed scope."}

Do not claim completion when a required check fails or cannot be run without
reporting the exact limitation.
`;
}

function renderWorkflow(workflow, checks) {
  return `# ${workflow.name}

> ${GENERATED_HEADER}

## Triggers

${bullets(workflow.triggers)}

## Steps

${workflow.steps.map((step, index) => {
    const check = step.checkId ? checks.get(step.checkId) : null;
    return `${index + 1}. ${step.required ? "**Required:** " : ""}${step.action}${check ? ` Run \`${check.command}\`.` : ""}`;
  }).join("\n")}
`;
}

function renderRootContract(blueprint) {
  const severityRank = { block: 0, warn: 1, guide: 2 };
  const highSignalRules = [...blueprint.rules]
    .sort((a, b) => severityRank[a.severity] - severityRank[b.severity])
    .slice(0, 20);
  const requiredChecks = blueprint.verification.filter((check) => check.required);
  return `## Gongxu Project Contract

### Project

- ${blueprint.project.summary}
- Read \`.ai/project/repo-map.md\` before substantial changes.
- Treat \`.ai/blueprint.json\` as the canonical project model.

### Before Changes

- Inspect the existing implementation and relevant project facts.
- Read a matching skill under \`.ai/skills/\` when one applies.
- Do not enforce proposed architecture as if it were confirmed.
- Keep changes inside the requested scope and preserve unrelated user work.

### Selected Rules

${highSignalRules.length > 0 ? highSignalRules.map((rule) => `- **${rule.severity.toUpperCase()} ${rule.id}:** ${rule.statement}`).join("\n") : "- No project-specific rules were selected; follow the verified workflows and repository evidence."}

### Verification

${requiredChecks.length > 0 ? requiredChecks.map((check) => `- \`${check.command}\` from \`${check.cwd || "."}\``).join("\n") : "- Run the checks applicable to the changed scope from `.ai/verification/checks.json`."}
- Do not claim completion unless required checks pass or the exact blocker is reported.

### Protected Changes

- Rules marked as blocking require their named check or approval path.
- Do not change confirmed architecture boundaries or public contracts as an
  incidental part of another task.
`;
}

function renderClaudeAdapter(existing) {
  const managedRegion = existing ? extractManagedBlock(existing) : null;
  const userContent = managedRegion ? existing.replace(managedRegion, "") : existing;
  const importLine = userContent?.includes("@AGENTS.md") ? "" : "@AGENTS.md\n\n";
  return `${importLine}## Gongxu Claude Code Adapter

- Use the shared project contract imported from \`AGENTS.md\`.
- Canonical project facts and workflows live under \`.ai/\`.
- Project skills are exposed through \`.claude/skills/gongxu-*\` wrappers.
- Treat instructions as guidance; rely on generated checks for enforcement.
`;
}

function renderSkillWrapper(skill, adapter) {
  const metadata = adapterSkillMetadata(skill, adapter);
  return `---
name: ${metadata.name}
description: ${JSON.stringify(metadata.description)}
---

# ${skill.name}

Locate the repository root and read
\`.ai/skills/${skill.id}/SKILL.md\` completely. Follow that canonical workflow,
its project context references, and its verification requirements. Do not
maintain independent instructions in this adapter.
`;
}

const VERIFICATION_RUNNER = `#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { readFileSync, realpathSync, statSync } from "node:fs";
import { dirname, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const verificationDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = realpathSync(resolve(verificationDirectory, "../.."));
const checks = JSON.parse(readFileSync(resolve(verificationDirectory, "checks.json"), "utf8"));
const selectedIndex = process.argv.indexOf("--check");
const selectedId = selectedIndex >= 0 ? process.argv[selectedIndex + 1] : null;

if (selectedIndex >= 0 && (!selectedId || selectedId.startsWith("--"))) {
  process.stderr.write("--check requires a check id.\\n");
  process.exit(2);
}

const selected = selectedId ? checks.filter((check) => check.id === selectedId) : checks;

if (selectedId && selected.length === 0) {
  process.stderr.write(\`Unknown verification check: \${selectedId}\\n\`);
  process.exit(2);
}

let requiredFailure = false;
for (const check of selected) {
  process.stdout.write(\`\\n[gongxu] \${check.id}: \${check.command}\\n\`);
  let checkDirectory;
  try {
    checkDirectory = realpathSync(resolve(repositoryRoot, check.cwd || "."));
    if (checkDirectory !== repositoryRoot && !checkDirectory.startsWith(\`\${repositoryRoot}\${sep}\`)) {
      throw new Error("working directory resolves outside the repository");
    }
    if (!statSync(checkDirectory).isDirectory()) throw new Error("working directory is not a directory");
  } catch (error) {
    process.stderr.write(\`[gongxu] \${check.id}: FAIL (\${error.message})\\n\`);
    if (check.required) requiredFailure = true;
    continue;
  }
  const result = spawnSync(check.command, {
    cwd: checkDirectory,
    env: process.env,
    shell: true,
    stdio: "inherit",
  });
  const passed = result.status === 0;
  process.stdout.write(\`[gongxu] \${check.id}: \${passed ? "PASS" : "FAIL"}\\n\`);
  if (!passed && check.required) requiredFailure = true;
}

process.exit(requiredFailure ? 1 : 0);
`;

export function renderArtifacts(blueprint, root) {
  const files = new Map();
  const checks = new Map(blueprint.verification.map((check) => [check.id, check]));

  addFile(files, ".ai/blueprint.json", json(blueprint), "source");
  addFile(files, ".ai/project/profile.md", renderProfile(blueprint));
  addFile(files, ".ai/project/facts.json", json({
    sourceRevision: blueprint.evidence.sourceRevision,
    facts: blueprint.evidence.facts,
    unknowns: blueprint.evidence.unknowns,
    answers: blueprint.evidence.answers,
    assumptions: blueprint.evidence.assumptions,
  }));
  addFile(files, ".ai/project/repo-map.md", renderRepoMap(blueprint));
  addFile(files, ".ai/architecture/current.md", renderCurrentArchitecture(blueprint));
  addFile(files, ".ai/architecture/model.json", json(blueprint.architecture));
  addFile(files, ".ai/architecture/boundaries.md", renderBoundaries(blueprint));
  addFile(files, ".ai/rules/catalog.json", json(blueprint.rules));
  const rulesByScope = new Map();
  for (const rule of blueprint.rules) {
    if (!rulesByScope.has(rule.scope)) rulesByScope.set(rule.scope, []);
    rulesByScope.get(rule.scope).push(rule);
  }
  for (const [scope, rules] of rulesByScope) {
    addFile(files, `.ai/rules/${scope}.md`, renderRuleScope(scope, rules));
  }

  for (const skill of blueprint.skills) {
    addSkillFile(files, `.ai/skills/${skill.id}/SKILL.md`, renderCanonicalSkill(skill, checks));
  }
  for (const workflow of blueprint.workflows) {
    addFile(files, `.ai/workflows/${workflow.id}.md`, renderWorkflow(workflow, checks));
  }
  if (blueprint.examples.length > 0) {
    addFile(files, ".ai/examples/catalog.json", json(blueprint.examples));
  }
  addFile(files, ".ai/verification/checks.json", json(blueprint.verification));
  addFile(files, ".ai/verification/run.mjs", VERIFICATION_RUNNER, "file", 0o755);

  const agentsPath = resolveInside(root, "AGENTS.md");
  const existingAgents = readTextIfExists(agentsPath);
  addFile(files, "AGENTS.md", mergeManagedBlock(existingAgents, renderRootContract(blueprint)), "region");

  if (blueprint.adapters.includes("claude")) {
    const claudePath = resolveInside(root, "CLAUDE.md");
    const existingClaude = readTextIfExists(claudePath);
    addFile(files, "CLAUDE.md", mergeManagedBlock(existingClaude, renderClaudeAdapter(existingClaude)), "region");
  }

  for (const skill of blueprint.skills) {
    if (blueprint.adapters.includes("codex")) {
      addSkillFile(files, `.agents/skills/gongxu-${skill.id}/SKILL.md`, renderSkillWrapper(skill, "codex"));
    }
    if (blueprint.adapters.includes("claude")) {
      addSkillFile(files, `.claude/skills/gongxu-${skill.id}/SKILL.md`, renderSkillWrapper(skill, "claude"));
    }
  }

  return files;
}
